export const MANUFACTURERS = [
  "21 LED",
  "3rd Coast Discs",
  "9Hill",
  "Above Ground Level",
  "Aerobie",
  "Albatross Disc Golf",
  "Alfa Discs",
  "All 4 Frisbee",
  "Amexpo Oy",
  "Andromeda M31 Discs",
  "AquaFlight Discs",
  "Arachnid Baskets",
  "Arsenal Discs",
  "Arroyo Disc Sports",
  "AstroDisc",
  "Axiom Discs",
  "Ballisdisc",
  "Bernoulli",
  "Best Disc Golf Discs",
  "Birdcage Baskets",
  "Birdie",
  "Black Zombie Disc Golf",
  "Castaway Discs",
  "Cheengz / Hyperflite",
  "Cheap Discs (Refuture Ventures Ab)",
  "Chili / Chilli Disc Golf",
  "CHING Disc Golf",
  "Chumba Discs",
  "Clash Discs",
  "Climo Disc Golf",
  "ColorYourGame",
  "Compound Discs",
  "Crosslap Disc Golf Parks",
  "Crown Me (Sunny Sporting Co. Ltd)",
  "Daredevil Discs",
  "Delta Mold LLC",
  "Deuz Disc Golf",
  "dgNomad",
  "DiSCORTi",
  "Disc 4 Fun",
  "Discape Disc Golf Inc.",
  "Disc Birdie",
  "Disc Golf Association (DGA)",
  "Disc Golf Monkey",
  "Disc Golf UK Ltd.",
  "Disc King",
  "Disc Mania (Discmania)",
  "Disc Monkey",
  "Disc Nation",
  "Disc Store",
  "Discount Disc Golf",
  "Discraft",
  "Disctroyer OU",
  "Dinosaur Discs",
  "Dino Discs",
  "Doomsday Discs",
  "Dynamic Discs",
  "Elevation Discs",
  "EV-7",
  "Eagle McMahon (brand entries / signature?)",
  "Fairway Discs",
  "Flight Discs",
  "Flying Discs (general/manufacturers)",
  "G-Form (disc-related gear)",
  "Gateway Disc Sports",
  "Goliath Discs",
  "Goeringer Discs",
  "Good Tree Disc Golf",
  "Gorilla Performance Discs",
  "Goto Disc Golf",
  "Gram Discs",
  "Grassland Discs",
  "GT Discs",
  "Guru",
  "H13 Disc Golf",
  "HIAARO (Giant Industry)",
  "Hobbysport",
  "Hole19 sarl",
  "Hero Disc",
  "Hive Disc Golf",
  "Hobie / Hobie-related (Aerobie heritage)",
  "Infinite Discs",
  "Innova",
  "Janus Discs",
  "Kastaplast",
  "Kela Discs",
  "Klotz Discs",
  "Lasting Plastic (generic / small shops)",
  "Latitude 64",
  "Legacy Discs",
  "Lone Star Disc",
  "MVP Disc Sports",
  "Millennium",
  "Millennium Golf",
  "Monsta Discs",
  "Moonshot Discs",
  "Norse Disc",
  "Notorious Discs",
  "Nova Discs",
  "Oddball Discs",
  "One Up Discs",
  "Pacer Discs",
  "PDGA Approved (category entries)",
  "Phi Discworks",
  "Pigment Discs",
  "Plastico Discs",
  "Prodigy Disc",
  "Prodiscus",
  "Proton Discs",
  "Pure Disc Golf",
  "Raptor Discs",
  "Reaper Discs",
  "Riteway Discs",
  "Roadrunner Discs",
  "Rock Solid Discs",
  "Saber Discs",
  "Sharkbite Discs",
  "Shrykes Discs",
  "Sidewinder Discs",
  "Souper Disc Co.",
  "Streamline Discs",
  "Storm Disc Golf",
  "Supersonic Discs",
  "Suomi Trading Ltd.",
  "Tactic Discs",
  "Team Discs (various player/label lines)",
  "Tomahawk Specialty Discs",
  "Torch Discs",
  "TOSY",
  "Trash Panda Disc Golf",
  "Trindem OÜ",
  "True Par Disc Golf",
  "Universal Play Disc Golf",
  "Vibram Disc Golf",
  "Viking Discs",
  "Visionary Disc Golf",
  "VORTExX",
  "WeldSpot Jarczyk Filip",
  "Westside Discs",
  "Yikun",
  "Zed Discs"
];
